name: "MBTech Cloud"
description: "Облачный сервис для удаленного доступа к Home Assistant"
version: "1.0.0"
slug: "mbtech_cloud"
url: "https://automationsolutions.ru/"
host_network: true
startup: application
boot: "auto"
init: false
map:
  - "share:rw"
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  Addres: "mars.mbtech.su"
  Token: ""
  Username: ""
  Password: ""
schema:
  Addres: str
  Token: password
  Username: str
  Password: password
